#include <pgmspace.h>

#define SECRET

const char WIFI_SSID[]="ENTER_WIFI_ADDRESS_HERE";
const char WIFI_PASSWORD[] ="ENTER_WIFI_PASSWORD_HERE";
const char AWS_IOT_ENDPOINT[]="ENTER_UNIQUE_AWS_ACCOUNTID_HERE";



// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
COPY_PASTE_YOUR_UINQUE_CA_CERTIFICATE_HERE
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
COPY_PASTE_YOUR_UINQUE_DEVICE_CERTIFICATE_HERE
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
COPY_PASTE_YOUR_UINQUE_DEVICE_KEY_HERE
-----END RSA PRIVATE KEY-----
)KEY";